import { readFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve } from "node:path";

/**
 * Remark plugin that replaces ```mermaid code blocks with inline SVG
 * from pre-rendered diagrams in .hermes/mermaid/.
 *
 * At build time, looks up each mermaid diagram by content hash in the
 * manifest generated by .hermes/scripts/extract-mermaid.py and inlines
 * the pre-rendered SVG directly into the HTML output.
 */
export default function remarkMermaid() {
	// During Astro build, CWD is the WebSite directory.
	// Project root is one level up.
	const ProjectRoot = resolve(process.cwd(), "..");
	const ManifestPath = resolve(ProjectRoot, ".hermes/mermaid/manifest.json");

	process.stderr.write(
		`[remarkMermaid] Plugin loading. CWD=${process.cwd()} ProjectRoot=${ProjectRoot}\n`,
	);
	process.stderr.write(
		`[remarkMermaid] Manifest at ${ManifestPath} exists=${existsSync(ManifestPath)}\n`,
	);

	// Build hash → SVG path lookup
	let HashToSvg: Record<string, string> | null = null;

	function LoadManifest() {
		if (HashToSvg) return;

		if (!existsSync(ManifestPath)) {
			process.stderr.write(
				`[remarkMermaid] Manifest not found at ${ManifestPath}\n`,
			);
			HashToSvg = {};
			return;
		}

		try {
			const Raw = readFileSync(ManifestPath, "utf-8");
			const Manifest = JSON.parse(Raw);
			const Diagrams: Record<string, any> = Manifest.diagrams || {};

			HashToSvg = {};
			for (const [_Id, Diag] of Object.entries(Diagrams)) {
				const D = Diag as Record<string, string>;
				const Hash = D["hash"];
				const Svg = D["svg"];
				if (Hash && Svg) {
					const SvgPath = resolve(ProjectRoot, Svg);
					if (existsSync(SvgPath)) {
						HashToSvg[Hash] = SvgPath;
					}
				}
			}

			process.stderr.write(
				`[remarkMermaid] Loaded ${
					Object.keys(HashToSvg).length
				} pre-rendered diagrams\n`,
			);
		} catch (Err) {
			process.stderr.write(
				`[remarkMermaid] Failed to load manifest: ${Err}\n`,
			);
			HashToSvg = {};
		}
	}

	return (Tree: { type: string; children?: any[] }) => {
		LoadManifest();
		if (!HashToSvg || Object.keys(HashToSvg).length === 0) return;
		Walk(Tree, HashToSvg, ProjectRoot);
	};
}

function Walk(
	Node: { type: string; children?: any[]; [key: string]: any },
	HashToSvg: Record<string, string>,
	ProjectRoot: string,
) {
	if (!Node.children) return;

	for (let I = 0; I < Node.children.length; I++) {
		const Child = Node.children[I];

		if (Child.type === "code" && Child.lang === "mermaid") {
			const Svg = RenderMermaidBlock(Child, HashToSvg, ProjectRoot);
			if (Svg) {
				Node.children[I] = Svg;
			}
		}

		Walk(Child, HashToSvg, ProjectRoot);
	}
}

function RenderMermaidBlock(
	Node: { value?: string; [key: string]: any },
	HashToSvg: Record<string, string>,
	_ProjectRoot: string,
): any | null {
	const Code = (Node.value || "").trim();
	if (!Code) return null;

	const Hash = createHash("sha256").update(Code).digest("hex").slice(0, 16);
	const SvgPath = HashToSvg[Hash];

	if (!SvgPath) {
		process.stderr.write(
			`[remarkMermaid] No rendered SVG found for hash ${Hash}\n`,
		);
		return {
			type: "paragraph",
			children: [
				{
					type: "text",
					value: `Diagram ${Hash} (unrendered)`,
				},
			],
		};
	}

	try {
		const SvgContent = readFileSync(SvgPath, "utf-8").trim();
		const SvgMatch = SvgContent.match(/<svg[\s\S]*?<\/svg>/i);
		if (!SvgMatch) {
			process.stderr.write(
				`[remarkMermaid] No SVG element in ${SvgPath}\n`,
			);
			return null;
		}

		const CleanSvg = SvgMatch[0]
			.replace(/\s+width="[^"]*"/, "")
			.replace(/\s+height="[^"]*"/, "")
			.replace("<svg", '<svg class="mermaid-diagram"');

		return {
			type: "html",
			value: CleanSvg,
		};
	} catch (Err) {
		process.stderr.write(
			`[remarkMermaid] Failed to read SVG ${SvgPath}: ${Err}\n`,
		);
		return null;
	}
}
