import type { RouteWorkerPolicy } from "./Policy.js";

declare global {
	interface Window {
		_ROUTE_WORKER: string;

		trustedTypes?: import("trusted-types").TrustedTypePolicyFactory;

		_POLICY_ROUTE?: {
			RouteWorker?: RouteWorkerPolicy;
		};
	}
}

declare const __DEV__: boolean;

declare const __INCREMENT__: string;

const INCREMENT =
	typeof __INCREMENT__ !== "undefined" ? __INCREMENT__ : "Initial";

const Path =
	typeof window._ROUTE_WORKER === "string"
		? window._ROUTE_WORKER
		: "/Worker.js";

const Scope = "/";

const Reload = "RouteWorkerReload";

const Log = __DEV__
	? (..._Message: any[]) => {
			console.log(`[Route Register ${INCREMENT}]`, ..._Message);
		}
	: () => {};

const ErrorLog = __DEV__
	? (..._Message: any[]) => {
			console.error(`[Route Register ${INCREMENT}]`, ..._Message);
		}
	: () => {};

const WarnLog = __DEV__
	? (..._Message: any[]) => {
			console.warn(`[Route Register ${INCREMENT}]`, ..._Message);
		}
	: () => {};

// In dev mode the service worker is not built (only generated by astro:build:done).
// Skip registration to avoid a 404 on /Worker.js polluting the console.
if ("serviceWorker" in navigator && !__DEV__) {
	const VersionKey = "RouteWorkerVersion";

	// ── Resolve the SW script URL (TrustedTypes or plain string) ──
	const ResolveSWURL = (): string | TrustedScriptURL => {
		if (window.trustedTypes) {
			const Policy = window._POLICY_ROUTE?.RouteWorker;

			if (!Policy) {
				throw new Error(
					"Required Trusted Types policy 'RouteWorker' not found.",
				);
			}

			return Policy.createScriptURL(Path);
		}

		return Path;
	};

	// ── Prompt a waiting SW to activate immediately ──
	const ActivateWaiting = (Registration: ServiceWorkerRegistration): void => {
		const Waiting = Registration.waiting;

		if (Waiting) {
			__DEV__ && Log("Found waiting SW, sending skipWaiting signal.");

			Waiting.postMessage({ Type: "skipWaiting" });
		}
	};

	// Tracks whether the SW was controlling this page when the script ran.
	// Hoisted so the controllerchange message handler can read it.
	let InitiallyControlled = !!navigator.serviceWorker.controller;

	// ── Main registration flow ──
	const Control = async () => {
		InitiallyControlled = !!navigator.serviceWorker.controller;

		__DEV__ &&
			Log(`Page controlled on script start: ${InitiallyControlled}`);

		try {
			const Registration = await navigator.serviceWorker.register(
				ResolveSWURL() as unknown as URL,
				{
					scope: Scope,
					type: "classic",
					// Always check the network for SW updates on navigation.
					// Without this, the browser may serve a stale SW from
					// HTTP cache for up to 24 hours.
					updateViaCache: "none",
				},
			);

			__DEV__ &&
				Log("Registration succeeded. Scope:", Registration.scope);

			// ── Handle a SW that is already waiting (e.g., installed while
			// a previous tab was still open) ──
			if (Registration.waiting) {
				__DEV__ && Log("SW already waiting on registration.");

				ActivateWaiting(Registration);
			}

			// ── Detect new SW versions installing ──
			Registration.addEventListener("updatefound", () => {
				const Installing = Registration.installing;

				if (!Installing) return;

				__DEV__ && Log("New SW version installing...");

				Installing.addEventListener("statechange", () => {
					if (
						Installing.state === "installed" &&
						navigator.serviceWorker.controller
					) {
						// A new SW is installed and waiting while an old one
						// still controls. Tell it to skip waiting.
						__DEV__ &&
							Log("New SW installed, prompting activation.");

						ActivateWaiting(Registration);
					}
				});
			});

			await navigator.serviceWorker.ready;

			// Trigger a background update check (network fetch of the SW
			// script). If a new version is found, the updatefound listener
			// above handles it.
			Registration.update().catch(() => {});
		} catch (_Error) {
			__DEV__ && ErrorLog("Registration failed:", _Error);
		}
	};

	// ── Controller change: a new SW just took over ──
	// This fires when skipWaiting + clients.claim() completes on the new SW.
	// Reload the page so the new route map / cache version takes effect.
	// Guard with sessionStorage to prevent infinite reload loops.
	navigator.serviceWorker.addEventListener("controllerchange", () => {
		__DEV__ && Log("Controller changed - new SW is active.");

		// Ask the new controller for its version
		navigator.serviceWorker.controller?.postMessage({
			Type: "Version:Check",
		});
	});

	// ── Version-aware reload ──
	// When the SW responds with its version, compare to the last known
	// version. If different, store the new version and reload once.
	navigator.serviceWorker.addEventListener("message", (Event) => {
		if (Event.data?.Type === "Version:Current") {
			const NewVersion = Event.data.Version as string;
			const OldVersion = sessionStorage.getItem(VersionKey);

			__DEV__ &&
				Log(
					`SW version: ${NewVersion} (previous: ${OldVersion ?? "none"})`,
				);

			if (OldVersion !== NewVersion) {
				sessionStorage.setItem(VersionKey, NewVersion);

				// Reload when:
				// 1. Version upgrade (OldVersion existed but changed), OR
				// 2. First-ever install and page was not already controlled -
				//    the SW just took over via clients.claim(); reload so it
				//    can intercept navigations (e.g. auth gate on /Dashboard).
				if (OldVersion !== null || !InitiallyControlled) {
					__DEV__ &&
						Log(
							"Reloading page (SW version change or first install).",
						);

					window.location.reload();
				}
			}
		}

		// Legacy: SW sends { Version: "New" } on activation
		if (Event.data?.Version === "New") {
			__DEV__ && Log("New SW version notification received.");

			const StoredVersion = sessionStorage.getItem(VersionKey);

			if (!StoredVersion) {
				// First time seeing this - request the actual version
				navigator.serviceWorker.controller?.postMessage({
					Type: "Version:Check",
				});
			}
		}
	});

	if (document.readyState === "loading") {
		document.addEventListener("DOMContentLoaded", Control);
	} else {
		Control();
	}
}

if (!("serviceWorker" in navigator)) {
	__DEV__ && WarnLog("Service Worker API not supported.");
}

export default {};
